version: "3.3"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=cms
      - POSTGRES_USER=cms_strapi
      - POSTGRES_PASSWORD=jvXxV2uC6dinxXKQb37H
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
